### ISSUE TITLE
Replace I18n manager

### ISSUE THREAD

**Issue by kwierchris** [OpusCapita/supplier#120]
Replace i18n Manager in https://github.com/OpusCapita/supplier/blob/develop/package.json#L52
with https://github.com/OpusCapita/i18n and remove **git** from https://github.com/OpusCapita/supplier/blob/develop/Dockerfile#L10

**Comment by lasong** [comment]
Implemented by https://github.com/OpusCapita/supplier/commit/9f123cf7bf52bcd0236c81f673a02e60f39d6c76
