### ISSUE TITLE
SupplierInformation - Missing supplier results in "Unable to render"

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/supplier#121]
After login as a supplier-user I am asked to fulfill my supplier data before I can proceed with InChannelConfig, but the Supplier editor shows an error:
![grafik](https://user-images.githubusercontent.com/26661092/29920014-d71f391c-8e4b-11e7-96db-2e6ac6bd3be5.png)

The reason is that - for which reason ever - the supplier entry is not existing - https://develop.businessnetwork.opuscapita.com/supplier/api/suppliers/<notexisting> returns null.

Either a proper error handling or/and (better?) the possibility to create the supplier is needed.

**Comment by lasong** [comment]
It's weird that the supplier does not exist. I will go for proper error handling

**Comment by lasong** [comment]
Fixed by https://github.com/OpusCapita/supplier/pull/131
