### ISSUE TITLE
SupplierRegistration - Country Of Registration empty or not?

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/supplier#124]
Part of OpusCapita/businessnetwork/issues/49

Country Of Registration is prefilled with the first Country in the country list, but it does hold a value when trying to save the entered data: Field cannot be blank.

This is missunderstanding for the user.
Please assure that the entry field is empty when opening the ui the first time.

**Comment by lasong** [comment]
To implement this, just add the prop `optional={true}` in Countries component
