### ISSUE TITLE
SupplierRegistration - Add info on mandatory fields

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/supplier#125]
Part of OpusCapita/businessnetwork/issues/49

Customer complains that "*" is not explained.
Please add an info at the botton of the form like
- en: "* Fields marked with asterisk are required fields." 
- de "* Die mit einem Sternchen gekennzeichneten Felder sind Pflichtfelder."

Additionally we need for the SupplierRegistration to bettr explain the login befind VAT Registration Number, Global Location Number and D-U-N-S Number. Mark it with "**" and add follogin explanation:
- en: "** One of the fields marked with two asterisk has to be provided." 
- de "** Eines der mit zwei Sternchen gekennzeichneten Felder muss bereitgestellt werden."

**Comment by lasong** [comment]
For now we would not explain the mandatory fields "*"  cause I think it's standard and if we are implementing it, it should be a standard across all services in opuscapita.
