### ISSUE TITLE
Company Registration form has invalid validation messages

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/supplier#133]
When registering company there are multiple "code-like" validation messages. Those should be informative. Language used was English. Have not tried with German.  
![image](https://user-images.githubusercontent.com/31001652/30051906-6adb844c-922c-11e7-9d1d-e6fe6dcc3153.png)

**Comment by lasong** [comment]
Fixed by https://github.com/OpusCapita/supplier/commit/5fb66159479ce35ffdb1f6d5440c843538798ed2
