### ISSUE TITLE
Supplier data editors lose state

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/supplier#135]
Go to supplier editor, add new address, save
Go to Home
Go to Supplier profile again (e.g. via dashboard button)
-> last saved address not showing (F5 makes it visible)

Same issue with contacts, probably bank accounts 
Reproduced and occurs ONLY on IE

**Comment by lasong** [comment]
These helped in finding a solution
 - http://jussi.hallila.com/2016/05/01/fixing-internet-explorer-for-your-react-es6-app.html
- https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser

**Comment by lasong** [comment]
Fixed  by https://github.com/OpusCapita/supplier/commit/0f0eb69f4fdd54a47b510d265d395c7ef05d84bc
