### ISSUE TITLE
Supplier gets company exists error

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/supplier#145]
https://businessnetwork.opuscapita.com/supplier/api/suppliers/exists?supplierName=agosense%20GmbH

returns true
but no company of that name exists.

Problem is token splitting and searching each token as GmbH already exists.
Fix by using exact match only .

**Comment by lasong** [comment]
Fixed by https://github.com/OpusCapita/supplier/commit/a71025648fabfeeab426159776fc300411c5fa61
