### ISSUE TITLE
User registration does not require verification link

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/supplier#156]
**Steps to reproduce:** 
1. Anonymous user registers via entry point for non-email media invitations. 
2. Do not enter verification code 
3. Log in. 

**Expected result:**
The user is told somehow that the verification code is needed. 
**Actual result:** 
The user can now move to registering a company. 
**Other info:** 
Might also occur for a invited user. Have not tried.

**Comment by lasong** [comment]
@blomqsu1 this bug does not belong to supplier service. What you described happens in the auth service https://github.com/OpusCapita/auth

**Comment by blomqsu1** [comment]
Moved the issue to auth.
