### ISSUE TITLE
Web element IDs are missing

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/supplier#160]
Web element IDs are missing in supplier. Those are needed for making test automation more stable. If the UI changes, the tests might unnecessary start to fail with current XPath and CSS selectors.

**Comment by kwierchris** [comment]
We have to very careful with the usage of IDs as we may reuse components or using the same components multiple times on the same page which would resolve in a conflicting browser behavior.

**Comment by lasong** [comment]
Implemented and resolved by https://github.com/OpusCapita/supplier/pull/179
