### ISSUE TITLE
Remove component properties

### ISSUE THREAD

**Issue by kwierchris** [OpusCapita/supplier#165]
We should remove the following component properties as they should be taken from the context object or are not needed anymore.

* locale (use this.context.locale)
* dateTimePattern (use this.context.i18n.formatDate() https://github.com/OpusCapita/i18n)
* actionUrl (just remove it and use the desired service URLs)

**Comment by lasong** [comment]
Actually `actionUrl` and `locale` props are not used anymore in any component, just forgot to remove them when calling the components. `dateTimePattern` has to be removed from code though.

**Comment by lasong** [comment]
Done
