### ISSUE TITLE
Try getting rid of raw SQL

### ISSUE THREAD

**Issue by kwierchris** [OpusCapita/supplier#169]
We should really get rid of this raw SQL queries as it already created a security issue that @sureshvarman-cronj fixed for us. So if it is not totally impossible, we should try to do these things using sequelize.

https://github.com/OpusCapita/supplier/blob/develop/src/server/queries/suppliers.js#L97-L132

**Comment by lasong** [comment]
I have to use raw queries here because there is no sequelize function for querying using mysql `MATCH`
