### ISSUE TITLE
Supplier Capabilities

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/supplier#176]
We need a data model for that

SupplierCapability
supplierId
capabilityId
createdOn
createdBy
changedOn
changedBy

Supplier hasMany SupplierCapability

We need a REST endpoint that allows enabling / disabling a capability.
api/suppliers/:supplierId/capabilities/:capabilityId

PUT to create / update
DELETE to remove
as we dont really have fields, no json payload is required for PUT,
but we need to return json with created object of course.

*Usage*

Support this in supplierDirectory by adding search filter for capability.
The possible values should be derived from select distinct capabilityId from SupplierCapability.

The reasoning here is that supplier itself is ignorant of what capabilities exist.

Implement capability creation in einvoice-send, once supplier has setup inChannelConfig fully, we need to call supplier to set the capability eInvoice.

If supplier loses inChannelConfig (status change from approved), do the DELETE api call

Supplier Directory should include a result column for each capability with a checked box if supplier has the capability.

**Comment by lasong** [comment]
Last part implemented by https://github.com/OpusCapita/einvoice-send/pull/140
