### ISSUE TITLE
Add recommendation for supplierId 

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/supplier#2]
Based on selection of SupplierName

**Comment by gr4per** [comment]
This is referring to companyInfo page in registration/onbaording flow.
The idea is to type-ahead-search for possibly matching supplier/company names already on the network portal in order to avoid duplicates.
This needs to include unique identifiers as they are being typed.

**Comment by gr4per** [comment]
This means that we pregenerate a unique supplier Id based on the company name (stripping white space and special chars, and append digits in case we have a duplicate)

**Comment by lasong** [comment]
Done by https://github.com/OpusCapita/supplier/pull/99
