### ISSUE TITLE
Refactor server-side i18n

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/supplier#223]
src/server/i18n

Files are not compatible with i18n approach as they declare map of functions when in fact they should declare key-value pairs.

**Comment by lasong** [comment]
Implemented by https://github.com/OpusCapita/supplier/commit/4dedd7584264f37bf7196a0dc26a5ae6d6b57ea8 and https://github.com/OpusCapita/supplier/commit/c3943e63bc7c5cd5740cebb39e6750b05e30f6fc
