### ISSUE TITLE
Data saving fails when adding supplier

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/supplier#23]
![image](https://cloud.githubusercontent.com/assets/22681804/24617863/75af1566-1895-11e7-934d-70fd81032b77.png)

**Comment by gr4per** [comment]
Client sees this error on console:
![image](https://cloud.githubusercontent.com/assets/22681804/24617934/b0c5e1fc-1895-11e7-9917-50c5858ef778.png)

**Comment by celber** [comment]
I have fixed transaction reference, promise returning and filter creation. I am not able to fix ER_NO_DEFAULT_FOR_FIELD: Field 'SupplierID' doesn't have a default value

**Comment by damianwojakowski** [comment]
NOTE: Add error logging

**Comment by damianwojakowski** [comment]
TODO: Add tests

**Comment by lasong** [comment]
Related to https://github.com/OpusCapitaBusinessNetwork/api-gw/issues/18. Being worked on now
