### ISSUE TITLE
Allow user supplier creation for self registration

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/supplier#28]
We need to solve the use case:
User is authenticated but has not assigned supplier company yet during onboarding.
User enters supplier in client form and client submits request to 
1. create supplier
2. assign user to this supplier

Doing two independent requests from client is not viable due to security issue: user could assign arbitrary suppliers.
Solution:
Extend suppliers/:supplierId POST endpoint 
 (if request user id is set and request user supplierid is null and request user customer id is null )then:
-call user service PUT users/:userId?tokenUpdate=true to update user's supplierId to value of request user id (this can be trusted because injected by api gw)

**Comment by lasong** [comment]
Implemented by #45
