### ISSUE TITLE
Publish supplier events via redis in case supplier is created/updated

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/supplier#50]
Use ocbesbn-redis-events
When supplier is created/updated publish event that contains supplier header as payload.
For creation, an event is to fire AFTER the user is associated to supplier.
The status of supplier should be "new" initially.
After assigning the user we can update supplier to have status "assigned".

Motivation: we need this in order to associate supplier to campaignContact in onboarding campaigns.

See also user service https://github.com/OpusCapita/user/issues/2

**Comment by lasong** [comment]
Implemented and resolved by #51
