### ISSUE TITLE
When registering supplier, continue button does not cause any visible action

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/supplier#56]
The page will not show any message or perform redirect.
After the explicit token refresh by client, the flow should be working but it isnt.

Expect: 
Continue button performs supplier provisioning and assignment of user to supplier on backend,
then client must navigate to bnp dashboard (will be welcome page because of new user profile settings)

**Comment by lasong** [comment]
The problem was with redis password of supplier in dev environment not included.
