### ISSUE TITLE
Add supplier directory component

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/supplier#58]
We need a place where we can search / browse suppliers based on criteria.
This e.g. needs to include Country / Region, Capabilties (e.g. connected services), commodity groups, rating etc.

This should be a rich UI in sim and a shareable react component in supplier that we can expose via bnp.

**Comment by lasong** [comment]
For a first implementation it should be similar to the onboarding search campaign UI https://develop.businessnetwork.opuscapita.com/onboarding/

**Comment by lasong** [comment]
Implemented and resolved by #159

**Comment by lasong** [comment]
First part of https://github.com/OpusCapita/businessnetwork/issues/22
