### ISSUE TITLE
/suppliers/{supplierId}/addresses endpoint not working

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/supplier#63]
Endpoint throws exception:
`
Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'SupplierID' in 'field list'
supplier_1     |     at Query.formatError (/home/node/supplier/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
supplier_1     |     at Query._callback (/home/node/supplier/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
supplier_1     |     at Query.Sequence.end (/home/node/supplier/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
supplier_1     |     at Query.ErrorPacket (/home/node/supplier/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
supplier_1     |     at Protocol._parsePacket (/home/node/supplier/node_modules/mysql/lib/protocol/Protocol.js:280:23)
supplier_1     |     at Parser.write (/home/node/supplier/node_modules/mysql/lib/protocol/Parser.js:75:12)
supplier_1     |     at Protocol.write (/home/node/supplier/node_modules/mysql/lib/protocol/Protocol.js:39:16)
supplier_1     |     at Socket.<anonymous> (/home/node/supplier/node_modules/mysql/lib/Connection.js:103:28)
supplier_1     |     at emitOne (events.js:96:13)
supplier_1     |     at Socket.emit (events.js:188:7)
supplier_1     |     at readableAddChunk (_stream_readable.js:176:18)
supplier_1     |     at Socket.Readable.push (_stream_readable.js:134:10)
supplier_1     |     at TCP.onread (net.js:547:20)
`

**Comment by lasong** [comment]
This is because the data model of Addresses was changed and some fields were added/removed, but the migration was done wrongly, so it did not run on dev. Quick fix will be to do this directly in the dev database. Will be done soon

**Comment by dzhitomirsky-sc** [comment]
Is there an ability to to run supplier service locally from scratch:
when I try to add opuscapita/supplier:dev image to _docker-compose.yml_ and start services i get
`
Executed (default): DELETE FROM `supplier-migrations` WHERE `name` = '20160217083000-simsupplier-migration.main.js' Elapsed time: 35ms
supplier_1     | Unhandled rejection SequelizeDatabaseError: ER_NO_DEFAULT_FOR_FIELD: Field 'CreatedOn' doesn't have a default value
supplier_1     |     at Query.formatError (/home/node/supplier/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
supplier_1     |     at Query._callback (/home/node/supplier/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
supplier_1     |     at Query.Sequence.end (/home/node/supplier/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
supplier_1     |     at Query.ErrorPacket (/home/node/supplier/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
supplier_1     |     at Protocol._parsePacket (/home/node/supplier/node_modules/mysql/lib/protocol/Protocol.js:280:23)
supplier_1     |     at Parser.write (/home/node/supplier/node_modules/mysql/lib/protocol/Parser.js:75:12)
supplier_1     |     at Protocol.write (/home/node/supplier/node_modules/mysql/lib/protocol/Protocol.js:39:16)
supplier_1     |     at Socket.<anonymous> (/home/node/supplier/node_modules/mysql/lib/Connection.js:103:28)
supplier_1     |     at emitOne (events.js:96:13)
supplier_1     |     at Socket.emit (events.js:188:7)
supplier_1     |     at readableAddChunk (_stream_readable.js:176:18)
supplier_1     |     at Socket.Readable.push (_stream_readable.js:134:10)
supplier_1     |     at TCP.onread (net.js:547:20)
`

**Comment by lasong** [comment]
Fixed by https://github.com/OpusCapita/supplier/commit/3de362327262fb16e0059c251d1a1a59d0299881
