### ISSUE TITLE
Clean supplier dashboard

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/supplier#75]
* Remove bottom right and bottom left list dummies
* Remove add users / add certificates / add financials buttons on top left, add button My Company Profile
that links to same dest as menu item Company /Profile
* Top right: remove Orders row, then make eInvoice connect driven by API in einvoice-send /api/config/inchannel. if you get a record and the status is activated, then show on UI as Connected 
if there is a record but in any other status, show on UI as Connecting, else as not connected

**Comment by lasong** [comment]
Implemented by #76
